### PR TITLE
Accumulate api records

### PR DESCRIPTION
**Pull request by edi-x**
I have added an accumulator to add the API records in the right archive interval to the database. This was mainly copy&past from the handling of the loop packets.

I have created a complete new database for my station and started the driver as test. Results are as desired.
I have not tested what happens when data is missing in the weatherflow cloud.

### CODE REVIEW

**Comment by edi-x** [comment]
I have done a test with gaps in the cloud data and fixed related issues.

**Comment by jjvdgeer** [comment]
Thanks

**Comment by jjvdgeer** [comment]
Err... haven't done pull requests before, I don't see the changes, I suppose I did something wrong. Hm.

**Comment by jjvdgeer** [comment]
That's more like it. Sorry for the confusion :)

**Comment by jjvdgeer** [comment]
@edi-x Haven't checked but what happens when archive_interval is smaller than 60? Should this:

if self._archive_interval == 60:

maybe be:

if self._archive_interval <= 60:

?

**Comment by edi-x** [comment]
@jjvdgeer, yes you are right. `if self._archive_interval <= 60:` is the better solution.

**Pull request merged**
